---
- hosts: kafka-nodes
  pre_tasks:
     - name: "Build hosts file"
       lineinfile: dest=/etc/hosts regexp='.*{{ ansible_hostname }}$' line="{{ ansible_default_ipv4.address }} {{ansible_hostname}}" state=present

  roles:
    - {
        role: ansible-java, jdk_version: '8',
        when: accept_oracle_licence
      }
    - {
        role: ansible-kafka, kafka: {
	    version: "0.10.2.1",
            scala_version: "2.12",
            mirror: "http://mirrors.sonic.net/apache",
            download_dir: "/tmp",
            install_dir: "/usr/local",
            server_properties: "real-server.properties",
            data_dir: "/opt/kafka/data"
	},zk_hosts: ["10.0.0.30"],zk_client_port: "2181",installed_java_version: "java-8-oracle"
      }
